### ISSUE TITLE
Is the script alive?

### ISSUE THREAD

**Issue by scarabhub** [the8nd/avitoparser#7]
При добавлении новых ссылок в консоль выдаёт бесконечно "403". Случаем это не означает, что скрипту беда?

**Comment by the8nd** [comment]
https://t.me/parseravbot Можете пользоваться по ссылке.

**Comment by the8nd** [comment]
А на какой операционке вы его запускаете?

> При добавлении новых ссылок в консоль выдаёт бесконечно "403". Случаем это не означает, что скрипту беда?

**Comment by scarabhub** [comment]
> А на какой операционке вы его запускаете?
> 
> > При добавлении новых ссылок в консоль выдаёт бесконечно "403". Случаем это не означает, что скрипту беда?

Windows 10, python

**Comment by the8nd** [comment]
> > А на какой операционке вы его запускаете?
> > > При добавлении новых ссылок в консоль выдаёт бесконечно "403". Случаем это не означает, что скрипту беда?
> 
> Windows 10, python

Поставьте WSL и на ней запустите. На windows и macOS авито стабильно отдает 403 ошибку. На ubuntu все нормально работает. Возможно, я пофикшу это, но чуть позже.
